import os
import time
from google import genai
from google.genai import types
from dotenv import load_dotenv

load_dotenv()
API_KEY = os.getenv("GEMINI_API_KEY")
VOICE_NAME = os.getenv("GEMINI_VOICE_NAME", "Aoede")
MODEL = os.getenv("GEMINI_TTS_MODEL", "gemini-2.5-flash-preview-tts")

DIRECTION = (
    "Speak like a captivating storyteller or documentary narrator revealing a profound and fascinating narrative. "
    "Do NOT sound like you are giving instructions or doing a tutorial. Instead, sound like you are "
    "uncovering a mystery or telling an enchanting fable. Use dynamic pacing, a tone of discovery, "
    "and dramatic pauses to let the words sink in. Make it beautiful, emotional, and thoroughly engaging."
)

TEXT = "There's a saying in the markets: a company's price is an opinion, but its data is the truth. To find the truth, we need the right magnifying glass."

print(f"Generating voice with {VOICE_NAME}...")

client = genai.Client(api_key=API_KEY)
for i in range(5):
    try:
        response = client.models.generate_content(
            model=MODEL,
            contents=[DIRECTION, TEXT],
            config=types.GenerateContentConfig(
                response_modalities=["AUDIO"],
                speech_config={"voice_config": {"prebuilt_voice_config": {"voice_name": VOICE_NAME}}}
            )
        )
        
        if hasattr(response, "parts") and response.parts:
            for p in response.parts:
                if hasattr(p, "inline_data") and p.inline_data:
                    out_path = "output/screener_story_test.wav"
                    with open(out_path, "wb") as f:
                        f.write(p.inline_data.data)
                    print(f"Success! Audio strictly generated by Gemini saved to {out_path}")
                    break
        break
    except Exception as e:
        print(f"Failed to generate, retrying in 12 seconds: {e}")
        time.sleep(12)
